name: Make test

on: [push, pull_request]

jobs:
  windows:
    name:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: echo "$VCPKG_INSTALLATION_ROOT"
    - shell: bash
      run: vcpkg install 'libevent[openssl]' krb5
    - shell: bash
      run: find C:/vcpkg/installed/x64-windows
