name: Make test

on: [push, pull_request]

jobs:
  windows:
    name:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: c:/vcpkg-cache
        key: ${{ runner.os }}-vcpkg
    - shell: bash
      run: install -d c:/vcpkg-cache
    - shell: bash
      run: echo "$VCPKG_INSTALLATION_ROOT"
    - shell: bash
      run: |
        vcpkg install --binarysource="clear;files,c:/vcpkg-cache,readwrite" 'openssl[tools]' 'libevent[openssl]' krb5
        echo "C:/vcpkg/installed/x64-windows/bin" >> "$GITHUB_PATH"
        echo "C:/vcpkg/installed/x64-windows/tools/openssl" >> "$GITHUB_PATH"
        cat "$GITHUB_PATH"
    - shell: bash
      run: find C:/vcpkg/installed/x64-windows
    - shell: bash
      run: |
        echo "$PATH"
        type openssl
        openssl version -a
