name: Make test

on: [push, pull_request]

jobs:
  windows:
    name:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: choco install openssl
    - shell: bash
      run: find "C:/Program Files/OpenSSL"
