name: Test Reusable

on:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v6
      - name: Hello
        run: echo ${{ runner.os }}
