name: CI sandbox

on: [push, pull_request, workflow_dispatch]

jobs:
  where:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'windows-2022', 'windows-2025']
    steps:
      - name: Where
        shell: bash
        run: ls "C:/Program Files (x86)/Windows Kits"/*/Debuggers/*/cdb.exe

  test:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v6
      - name: Find vcvarsall.bat
        shell: bash
        run: find 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise' -iname 'vcvarsall.bat'
      - name: Inspect
        shell: bash
        run: find 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise' -maxdepth 5
      - name: info
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          echo %PATH%
          cdb foo
