name: CI sandbox

on: [push, pull_request, workflow_dispatch]

jobs:
  where:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'windows-2022', 'windows-2025']
    steps:
      - uses: actions/checkout@v6
      - name: Install cdb
        run: python installcdb.py
      - name: Where
        shell: bash
        run: ls "C:/Program Files (x86)/Windows Kits"/*/Debuggers/*/cdb.exe

  test:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v6
      - name: reginfo
        run: >
            python regdump.py
            "Software\Microsoft\Windows NT\CurrentVersion\AeDebug"
            "Software\Wow6432Node\Microsoft\Windows NT\CurrentVersion\AeDebug"
            "Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
